ci: regenerate config via make_travis_yml_2.hs

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,163 +1,140 @@
-# Use new container infrastructure to enable caching
+# This Travis job script has been generated by a script via
+#
+#   runghc make_travis_yml_2.hs 'jose.cabal' '--ghc-head'
+#
+# For more information, see https://github.com/haskell-CI/haskell-ci
+#
+language: c
 sudo: false
 
-# Choose a lightweight base image; we provide our own build tools.
-language: c
+git:
+  submodules: false  # whether to recursively clone submodules
 
-# Caching so the next build will be fast too.
 cache:
   directories:
-  - $HOME/.stack
-  - $HOME/.cabsnap
-  - $HOME/.cabal/packages
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
 
 before_cache:
   - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
-  - test -n "$STACK_ARGS" && cp -a $HOME/.ghc $HOME/.cabsnap/ghc || true
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+
+  - rm -rfv $HOME/.cabal/packages/head.hackage
 
 matrix:
   include:
-  - env: STACK_ARGS="--resolver lts-5"
-    compiler: ": #stackage lts-5 (ghc-7.10.3)"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: STACK_ARGS="--resolver lts-6"
-    compiler: ": #stackage lts-6 (ghc-7.10.3)"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: STACK_ARGS="--resolver lts-7"
-    compiler: ": #stackage lts-7 (ghc-8.0.1)"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: STACK_ARGS="--resolver lts-8"
-    compiler: ": #stackage lts-8 (ghc-8.0.2)"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: STACK_ARGS="--resolver lts-9"
-    compiler: ": #stackage lts-9 (ghc-8.0.2)"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: STACK_ARGS="--resolver lts-10"
-    compiler: ": #stackage lts-10 (ghc-8.2.2)"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: STACK_ARGS="--resolver lts-11"
-    compiler: ": #stackage lts-11 (ghc-8.2.2)"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: STACK_ARGS="--resolver lts-12"
-    compiler: ": #stackage lts-12 (ghc-8.4.4)"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: STACK_ARGS="--resolver nightly"
-    compiler: ": #stackage nightly"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: CABALVER=1.24 GHCVER=7.10.3
-    compiler: ": #GHC 7.10.3"
-    addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3], sources: [hvr-ghc]}}
-
-  - env: CABALVER=1.24 GHCVER=8.0.2
-    compiler: ": #GHC 8.0.2"
-    addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
-
-  - env: CABALVER=2.0 GHCVER=8.2.2
-    compiler: ": #GHC 8.2.2"
-    addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.2], sources: [hvr-ghc]}}
-
-  - env: CABALVER=2.2 GHCVER=8.4.4
-    compiler: ": #GHC 8.4.4"
-    addons: {apt: {packages: [cabal-install-2.2,ghc-8.4.4], sources: [hvr-ghc]}}
-
-  - env: CABALVER=2.4 GHCVER=8.6.3
-    compiler: ": #GHC 8.6.3"
-    addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.3], sources: [hvr-ghc]}}
-
-  - env: CABALVER=head GHCVER=head
-    compiler: ": #GHC HEAD"
-    addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.6.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.6.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.4.4"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.4.4], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.2.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.2.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.0.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.10.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-7.10.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-head"
+      env: GHCHEAD=true
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-head], sources: [hvr-ghc]}}
 
   allow_failures:
-  - env: CABALVER=head GHCVER=head
-  - env: STACK_ARGS="--resolver nightly"
+    - compiler: "ghc-head"
 
 before_install:
-# Using compiler above sets CC to an invalid value, so unset it
-- unset CC
-
-- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
-- export PATH=$HOME/.local/bin:$PATH
-- mkdir -p ~/.local/bin
-
-# Download and unpack the stack executable
-- |
-  test -n "$STACK_ARGS" || return 0
-  travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
-
-  # Use the more reliable S3 mirror of Hackage
-  mkdir -p $HOME/.cabal
-  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
-  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config
-  stack --no-terminal $STACK_ARGS setup
-  echo "$(stack $STACK_ARGS ghc -- --version) [$(stack $STACK_ARGS ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - HC=${CC}
+  - HCPKG=${HC/ghc/ghc-pkg}
+  - unset CC
+  - ROOTDIR=$(pwd)
+  - mkdir -p $HOME/.local/bin
+  - "PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$HOME/local/bin:$PATH"
+  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
+  - echo $HCNUMVER
 
 install:
-- |
-  test -n "$CABALVER" || return 0
-  cabal --version
-  echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
-  if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
-  then
-    zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz > \
-         $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
-  fi
-  travis_retry cabal update -v
-  sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
-  cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt
-  sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
+  - cabal --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - BENCH=${BENCH---enable-benchmarks}
+  - TEST=${TEST---enable-tests}
+  - HADDOCK=${HADDOCK-true}
+  - UNCONSTRAINED=${UNCONSTRAINED-true}
+  - NOINSTALLEDCONSTRAINTS=${NOINSTALLEDCONSTRAINTS-false}
+  - GHCHEAD=${GHCHEAD-false}
+  - travis_retry cabal update -v
+  - "sed -i.bak 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config"
+  - rm -fv cabal.project cabal.project.local
+  # Overlay Hackage Package Index for GHC HEAD: https://github.com/hvr/head.hackage
+  - |
+    if $GHCHEAD; then
+      sed -i 's/-- allow-newer: .*/allow-newer: *:base/' ${HOME}/.cabal/config
+      for pkg in $($HCPKG list --simple-output); do pkg=$(echo $pkg | sed 's/-[^-]*$//'); sed -i "s/allow-newer: /allow-newer: *:$pkg, /" ${HOME}/.cabal/config; done
 
-  # check whether current requested install-plan matches cached package-db snapshot
-  if diff -u $HOME/.cabsnap/installplan.txt installplan.txt;
-  then
-    echo "cabal build-cache HIT";
-    rm -rfv .ghc;
-    cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
-    cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
-  else
-    echo "cabal build-cache MISS";
-    rm -rf $HOME/.cabsnap;
-    mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
-    cabal install --only-dependencies --enable-tests --enable-benchmarks;
-  fi
+      echo 'repository head.hackage'                                                        >> ${HOME}/.cabal/config
+      echo '   url: http://head.hackage.haskell.org/'                                       >> ${HOME}/.cabal/config
+      echo '   secure: True'                                                                >> ${HOME}/.cabal/config
+      echo '   root-keys: 07c59cb65787dedfaef5bd5f987ceb5f7e5ebf88b904bbd4c5cbdeb2ff71b740' >> ${HOME}/.cabal/config
+      echo '              2e8555dde16ebd8df076f1a8ef13b8f14c66bad8eafefd7d9e37d0ed711821fb' >> ${HOME}/.cabal/config
+      echo '              8f79fd2389ab2967354407ec852cbe73f2e8635793ac446d09461ffb99527f6e' >> ${HOME}/.cabal/config
+      echo '   key-threshold: 3'                                                            >> ${HOME}/.cabal.config
 
-  # snapshot package-db on cache miss
-  if [ ! -d $HOME/.cabsnap ];
-  then
-    echo "snapshotting package-db to build-cache";
-    mkdir $HOME/.cabsnap;
-    cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
-    cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
-  fi
+      grep -Ev -- '^\s*--' ${HOME}/.cabal/config | grep -Ev '^\s*$'
 
-- |
-  test -n "$STACK_ARGS" || return 0
-  [ -d $HOME/.cabsnap/ghc ] && cp -a $HOME/.cabsnap/ghc $HOME/.ghc || true
+      cabal new-update head.hackage -v
+    fi
+  - grep -Ev -- '^\s*--' ${HOME}/.cabal/config | grep -Ev '^\s*$'
+  - "printf 'packages: \".\"\\n' > cabal.project"
+  - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
+  - touch cabal.project.local
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- jose | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  - if [ -f "./configure.ac" ]; then
+      (cd "." && autoreconf -i);
+    fi
+  - rm -f cabal.project.freeze
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --project-file="cabal.project" --dep -j2 all
+  - rm -rf .ghc.environment.* "."/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
 
-
-
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-- if test -n "$STACK_ARGS" ; then stack --no-terminal $STACK_ARGS test --bench --only-dependencies ; fi
-- if test -n "$STACK_ARGS" ; then stack --no-terminal $STACK_ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps ; fi
+  # test that source-distributions can be generated
+  - cabal new-sdist all
+  - mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
+  - cd ${DISTDIR} || false
+  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - "printf 'packages: jose-*/*.cabal\\n' > cabal.project"
+  - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
+  - touch cabal.project.local
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- jose | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  # this builds all libraries and executables (without tests/benchmarks)
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
 
-- if test -n "$CABALVER" -a -f configure.ac ; then autoreconf -i ; fi
-- if test -n "$CABALVER" ; then cabal configure --enable-tests --enable-benchmarks -v2 ; fi  # -v2 provides useful information for debugging
-- if test -n "$CABALVER" ; then cabal build -f demos ; fi   # this builds all libraries and executables (including tests/benchmarks)
-- if test -n "$CABALVER" ; then cabal test ; fi
-- if test -n "$CABALVER" ; then cabal check ; fi
-- if test -n "$CABALVER" ; then cabal sdist ; fi  # tests that a source-distribution can be generated
+  # build & run tests, build benchmarks
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+  - if [ "x$TEST" = "x--enable-tests" ]; then cabal new-test -w ${HC} ${TEST} ${BENCH} all; fi
 
-# Check that the resulting source distribution can be built & installed.
-# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
-# `cabal install --force-reinstalls dist/*-*.tar.gz`
-- if test -n "$CABALVER" ; then SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && (cd dist && cabal install --force-reinstalls "$SRC_TGZ") ; fi
+  # cabal check
+  - (cd jose-* && cabal check)
+
+  # haddock
+  - if $HADDOCK; then cabal new-haddock -w ${HC} ${TEST} ${BENCH} all; else echo "Skipping haddock generation";fi
+
+  # Build without installed constraints for packages in global-db
+  - if $UNCONSTRAINED; then rm -f cabal.project.local; echo cabal new-build -w ${HC} --disable-tests --disable-benchmarks all; else echo "Not building without installed constraints"; fi
+
+# REGENDATA ["jose.cabal","--ghc-head"]
+# EOF
